/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import model.ItemLivro;
import model.Livro;
import util.Validador;

/**
 *
 * @author mzynich
 */
public class FrameCriarEditarLivro extends javax.swing.JFrame {

    private boolean edicao;
    private ItemLivro itemLivro;
    private static FrameListarLivro framePai;

    /**
     * Creates new form FrameCriarLivro
     *
     * @param framePai
     */
    public FrameCriarEditarLivro(FrameListarLivro framePai) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.framePai = framePai;
        this.edicao = false;
        jTextField7.setEditable(false);
    }

    public FrameCriarEditarLivro(FrameListarLivro framePai, ItemLivro livro) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.framePai = framePai;
        this.edicao = true;
        this.itemLivro = livro;
        jTextField1.setText(livro.getLivro().getId() + "");
        jTextField2.setText(livro.getLivro().getISBN());
        jTextField3.setText(livro.getLivro().getNome());
        jTextField4.setText(livro.getLivro().getAutor());
        jTextField5.setText(livro.getLivro().getEditora());
        jTextField8.setText(livro.getLivro().getAno() + "");
        jTextField6.setText(livro.getQuantidadeTotal() + "");
        jTextField7.setText(livro.getQuantidadeDisponivel() + "");
    }

    /**
     * Creates new form FrameCriarLivro
     */
    public FrameCriarEditarLivro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.edicao = false;
        jTextField7.setEditable(false);
    }

    /**
     * Cria um formulário para edição de um livro
     *
     * @param livro
     */
    public FrameCriarEditarLivro(ItemLivro livro) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.edicao = true;
        this.itemLivro = livro;
        jTextField1.setText(livro.getLivro().getId() + "");
        jTextField2.setText(livro.getLivro().getISBN());
        jTextField3.setText(livro.getLivro().getNome());
        jTextField4.setText(livro.getLivro().getAutor());
        jTextField5.setText(livro.getLivro().getEditora());
        jTextField8.setText(livro.getLivro().getAno() + "");
        jTextField6.setText(livro.getQuantidadeTotal() + "");
        jTextField7.setText(livro.getQuantidadeDisponivel() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de livro");
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("ISBN");

        jLabel3.setText("Nome");

        jLabel4.setText("Autor");

        jLabel5.setText("Editora");

        jLabel6.setText("Quantidade disponível");

        jLabel7.setText("Quantidade total");

        jTextField1.setEditable(false);
        jTextField1.setColumns(20);

        jTextField2.setColumns(20);

        jTextField3.setColumns(20);

        jTextField4.setColumns(20);

        jTextField5.setColumns(20);

        jTextField6.setColumns(20);

        jTextField7.setColumns(20);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField5)
                                .addComponent(jTextField4)
                                .addComponent(jTextField3)
                                .addComponent(jTextField2)
                                .addComponent(jTextField1)
                                .addComponent(jTextField8))
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botão cancelar
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Botão confirmar
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Edição de livro
        if (edicao) {
            Livro livro = itemLivro.getLivro();
            if (validaCampos(true)) {
                livro.setISBN(jTextField2.getText());
                livro.setNome(jTextField3.getText());
                livro.setAutor(jTextField4.getText());
                livro.setEditora(jTextField5.getText());
                livro.setAno(Integer.parseInt(jTextField8.getText()));
                new servico.ServicoItemLivro().editaLivro(livro);
                itemLivro.setLivro(livro);
                itemLivro.setQuantidadeTotal(Integer.parseInt(jTextField6.getText()));
                itemLivro.setQuantidadeDisponivel(Integer.parseInt(jTextField7.getText()));
                new servico.ServicoItemLivro().editaItemLivro(itemLivro);
                JOptionPane.showMessageDialog(this, "Livro editado com sucesso.");
                this.dispose();
                if (framePai != null) {
                    framePai.atualizaTabela();
                }
            }
            //Criação de livro
        } else {
            if (validaCampos(false)) {
                new servico.ServicoItemLivro().addItemLivro(new ItemLivro(
                        new Livro(jTextField2.getText(), jTextField3.getText(), jTextField4.getText(),
                                jTextField5.getText(), Integer.parseInt(jTextField6.getText())), Integer.parseInt(jTextField6.getText())));
                JOptionPane.showMessageDialog(this, "Livro criado com sucesso.");
                this.dispose();
                if (framePai != null) {
                    framePai.atualizaTabela();
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Método para validar os campos JTextField desse Frame
     *
     * @return true se os campos forem válidos e false se não
     */
    private boolean validaCampos(boolean edicao) {
        try {
            if (edicao) {
                if (Validador.ISBNValido(jTextField2.getText())
                        && Validador.nomeLivroValido(jTextField3.getText())
                        && Validador.autorValido(jTextField4.getText())
                        && Validador.editoraValida(jTextField5.getText())
                        && Validador.anoValido(Integer.parseInt(jTextField8.getText()))
                        && Validador.quantidadeValida(Integer.parseInt(jTextField6.getText()))
                        && Validador.quantidadeValida(Integer.parseInt(jTextField7.getText()))) {
                    if (Integer.parseInt(jTextField7.getText()) <= Integer.parseInt(jTextField6.getText())) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Quantidade disponível deve ser menor ou igual à quantidade total.", "Erro", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                }
            } else {
                if (Validador.ISBNValido(jTextField2.getText())
                        && Validador.nomeLivroValido(jTextField3.getText())
                        && Validador.autorValido(jTextField4.getText())
                        && Validador.editoraValida(jTextField5.getText())
                        && Validador.anoValido(Integer.parseInt(jTextField8.getText()))
                        && Validador.quantidadeValida(Integer.parseInt(jTextField6.getText()))) {
                    return true;
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ano e quantidades devem ser números.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCriarEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCriarEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCriarEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCriarEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCriarEditarLivro(framePai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
